name: Deploy release
on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.12.2

        - name: Terraform Init and Apply
          working-directory: ${{ matrix.env }}
          run: |
            terraform init -reconfigure
            terraform apply -auto-approve 

        - name: Build artifact zip
          run: |
            TAG=${{ steps.tag_push.outputs.release_tag }}
            mkdir -p artifact-content/module
            cp -r ${{ matrix.env }} artifact-content/${{ matrix.env }}
            cp -r module/${{ matrix.env }} artifact-content/module/${{ matrix.env }}
            cd artifact-content
            zip -r ../build-artifacts-${TAG}.zip ./*

        - name: Create GitHub Release and upload artifact
          uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: ${{ secrets.TOKEN_GITHUB }}
            automatic_release_tag: ${{ steps.tag_push.outputs.release_tag }}
            files: build-artifacts-${{ steps.tag_push.outputs.release_tag }}.zip

        - name: Upload build artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.env }}-build-artifact-${{ steps.tag_push.outputs.release_tag }}
            path: build-artifacts-${{ steps.tag_push.outputs.release_tag }}.zip